.PHONY: clean All

All:
	@echo "----------Building project:[ TaskD - Debug ]----------"
	@cd "TaskD" && "$(MAKE)" -f  "TaskD.mk"
clean:
	@echo "----------Cleaning project:[ TaskD - Debug ]----------"
	@cd "TaskD" && "$(MAKE)" -f  "TaskD.mk" clean
